
name: pian
description: A text editor

language: GHC2021

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - LambdaCase
  - NoStarIsType
  - TypeFamilies
  - DefaultSignatures
  - UndecidableInstances

dependencies:
  - base
  - text
  - large-anon
  - finite-typelits
  - ghc-typelits-knownnat
  - ghc-typelits-natnormalise

library:
   source-dirs: src
   default-extensions:
   - TemplateHaskell
   dependencies: 
   - cursor
   - brick
   - cursor-brick
   - vty
   - directory
   - path
   - path-io
   - pretty-show
   - microlens
   - microlens-th
   - microlens-mtl
   ghc-options: 
     - -fplugin=Data.Record.Anon.Plugin 
     - -fplugin=GHC.TypeLits.KnownNat.Solver
     - -fplugin=GHC.TypeLits.Normalise

executables:
  pian-go:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pian

